// states.js
export const states = [
  { key: "Alabama", value: "alabama" },
  { key: "Alaska", value: "alaska" },
  { key: "Arizona", value: "arizona" },
  { key: "Arkansas", value: "arkansas" },
  { key: "California", value: "california" },
  { key: "Colorado", value: "colorado" },
  { key: "Connecticut", value: "connecticut" },
  { key: "District of Columbia", value: "district_of_columbia" },
  { key: "Delaware", value: "delaware" },
  { key: "Florida", value: "florida" },
  { key: "Georgia", value: "georgia" },
  { key: "Hawaii", value: "hawaii" },
  { key: "Idaho", value: "idaho" },
  { key: "Illinois", value: "illinois" },
  { key: "Indiana", value: "indiana" },
  { key: "Iowa", value: "iowa" },
  { key: "Kansas", value: "kansas" },
  { key: "Kentucky", value: "kentucky" },
  { key: "Louisiana", value: "louisiana" },
  { key: "Maine", value: "maine" },
  { key: "Maryland", value: "maryland" },
  { key: "Massachusetts", value: "massachusetts" },
  { key: "Michigan", value: "michigan" },
  { key: "Minnesota", value: "minnesota" },
  { key: "Mississippi", value: "mississippi" },
  { key: "Missouri", value: "missouri" },
  { key: "Montana", value: "montana" },
  { key: "Nebraska", value: "nebraska" },
  { key: "Nevada", value: "nevada" },
  { key: "New Hampshire", value: "new_hampshire" },
  { key: "New Jersey", value: "new_jersey" },
  { key: "New Mexico", value: "new_mexico" },
  { key: "New York", value: "new_york" },
  { key: "North Carolina", value: "north_carolina" },
  { key: "North Dakota", value: "north_dakota" },
  { key: "Ohio", value: "ohio" },
  { key: "Oklahoma", value: "oklahoma" },
  { key: "Oregon", value: "oregon" },
  { key: "Pennsylvania", value: "pennsylvania" },
  { key: "Rhode Island", value: "rhode_island" },
  { key: "South Carolina", value: "south_carolina" },
  { key: "South Dakota", value: "south_dakota" },
  { key: "Tennessee", value: "tennessee" },
  { key: "Texas", value: "texas" },
  { key: "Utah", value: "utah" },
  { key: "Vermont", value: "vermont" },
  { key: "Virginia", value: "virginia" },
  { key: "Washington", value: "washington" },
  { key: "West Virginia", value: "west_virginia" },
  { key: "Wisconsin", value: "wisconsin" },
  { key: "Wyoming", value: "wyoming" },
  { key: "American Samoa", value: "american_samoa" },
  { key: "Guam", value: "guam" },
  { key: "Northern Mariana Islands", value: "northern_mariana_islands" },
  { key: "Puerto Rico", value: "puerto_rico" },
  {
    key: "United States Minor Outlying Islands",
    value: "united_states_minor_outlying_islands",
  },
  { key: "Virgin Islands", value: "virgin_islands" },
];
export const zoomTimezones = [
  { value: "Pacific/Midway", text: "Midway Island, Samoa" },
  { value: "Pacific/Pago_Pago", text: "Pago Pago" },
  { value: "Pacific/Honolulu", text: "Hawaii" },
  { value: "America/Anchorage", text: "Alaska" },
  { value: "America/Vancouver", text: "Vancouver" },
  { value: "America/Los_Angeles", text: "Pacific Time (US and Canada)" },
  { value: "America/Tijuana", text: "Tijuana" },
  { value: "America/Edmonton", text: "Edmonton" },
  { value: "America/Denver", text: "Mountain Time (US and Canada)" },
  { value: "America/Phoenix", text: "Arizona" },
  { value: "America/Mazatlan", text: "Mazatlan" },
  { value: "America/Winnipeg", text: "Winnipeg" },
  { value: "America/Regina", text: "Saskatchewan" },
  { value: "America/Chicago", text: "Central Time (US and Canada)" },
  { value: "America/Mexico_City", text: "Mexico City" },
  { value: "America/Guatemala", text: "Guatemala" },
  { value: "America/El_Salvador", text: "El Salvador" },
  { value: "America/Managua", text: "Managua" },
  { value: "America/Costa_Rica", text: "Costa Rica" },
  { value: "America/Montreal", text: "Montreal" },
  { value: "America/New_York", text: "Eastern Time (US and Canada)" },
  { value: "America/Indianapolis", text: "Indiana (East)" },
  { value: "America/Panama", text: "Panama" },
  { value: "America/Bogota", text: "Bogota" },
  { value: "America/Lima", text: "Lima" },
  { value: "America/Halifax", text: "Halifax" },
  { value: "America/Puerto_Rico", text: "Puerto Rico" },
  { value: "America/Caracas", text: "Caracas" },
  { value: "America/Santiago", text: "Santiago" },
  { value: "America/St_Johns", text: "Newfoundland and Labrador" },
  { value: "America/Montevideo", text: "Montevideo" },
  { value: "America/Araguaina", text: "Brasilia" },
  { value: "America/Argentina/Buenos_Aires", text: "Buenos Aires, Georgetown" },
  { value: "America/Godthab", text: "Greenland" },
  { value: "America/Sao_Paulo", text: "Sao Paulo" },
  { value: "Atlantic/Azores", text: "Azores" },
  { value: "Canada/Atlantic", text: "Atlantic Time (Canada)" },
  { value: "Atlantic/Cape_Verde", text: "Cape Verde Islands" },
  { value: "UTC", text: "Universal Time UTC" },
  { value: "Etc/Greenwich", text: "Greenwich Mean Time" },
  { value: "Europe/Belgrade", text: "Belgrade, Bratislava, Ljubljana" },
  { value: "CET", text: "Sarajevo, Skopje, Zagreb" },
  { value: "Atlantic/Reykjavik", text: "Reykjavik" },
  { value: "Europe/Dublin", text: "Dublin" },
  { value: "Europe/London", text: "London" },
  { value: "Europe/Lisbon", text: "Lisbon" },
  { value: "Africa/Casablanca", text: "Casablanca" },
  { value: "Africa/Nouakchott", text: "Nouakchott" },
  { value: "Europe/Oslo", text: "Oslo" },
  { value: "Europe/Copenhagen", text: "Copenhagen" },
  { value: "Europe/Brussels", text: "Brussels" },
  {
    value: "Europe/Berlin",
    text: "Amsterdam, Berlin, Rome, Stockholm, Vienna",
  },
  { value: "Europe/Helsinki", text: "Helsinki" },
  { value: "Europe/Amsterdam", text: "Amsterdam" },
  { value: "Europe/Rome", text: "Rome" },
  { value: "Europe/Stockholm", text: "Stockholm" },
  { value: "Europe/Vienna", text: "Vienna" },
  { value: "Europe/Luxembourg", text: "Luxembourg" },
  { value: "Europe/Paris", text: "Paris" },
  { value: "Europe/Zurich", text: "Zurich" },
  { value: "Europe/Madrid", text: "Madrid" },
  { value: "Africa/Bangui", text: "West Central Africa" },
  { value: "Africa/Algiers", text: "Algiers" },
  { value: "Africa/Tunis", text: "Tunis" },
  { value: "Africa/Harare", text: "Harare, Pretoria" },
  { value: "Africa/Nairobi", text: "Nairobi" },
  { value: "Europe/Warsaw", text: "Warsaw" },
  { value: "Europe/Prague", text: "Prague, Bratislava" },
  { value: "Europe/Budapest", text: "Budapest" },
  { value: "Europe/Sofia", text: "Sofia" },
  { value: "Europe/Istanbul", text: "Istanbul" },
  { value: "Europe/Athens", text: "Athens" },
  { value: "Europe/Bucharest", text: "Bucharest" },
  { value: "Asia/Nicosia", text: "Nicosia" },
  { value: "Asia/Beirut", text: "Beirut" },
  { value: "Asia/Damascus", text: "Damascus" },
  { value: "Asia/Jerusalem", text: "Jerusalem" },
  { value: "Asia/Amman", text: "Amman" },
  { value: "Africa/Tripoli", text: "Tripoli" },
  { value: "Africa/Cairo", text: "Cairo" },
  { value: "Africa/Johannesburg", text: "Johannesburg" },
  { value: "Europe/Moscow", text: "Moscow" },
  { value: "Asia/Baghdad", text: "Baghdad" },
  { value: "Asia/Kuwait", text: "Kuwait" },
  { value: "Asia/Riyadh", text: "Riyadh" },
  { value: "Asia/Bahrain", text: "Bahrain" },
  { value: "Asia/Qatar", text: "Qatar" },
  { value: "Asia/Aden", text: "Aden" },
  { value: "Asia/Tehran", text: "Tehran" },
  { value: "Africa/Khartoum", text: "Khartoum" },
  { value: "Africa/Djibouti", text: "Djibouti" },
  { value: "Africa/Mogadishu", text: "Mogadishu" },
  { value: "Asia/Dubai", text: "Dubai" },
  { value: "Asia/Muscat", text: "Muscat" },
  { value: "Asia/Baku", text: "Baku, Tbilisi, Yerevan" },
  { value: "Asia/Kabul", text: "Kabul" },
  { value: "Asia/Yekaterinburg", text: "Yekaterinburg" },
  { value: "Asia/Tashkent", text: "Islamabad, Karachi, Tashkent" },
  { value: "Asia/Calcutta", text: "India" },
  { value: "Asia/Kathmandu", text: "Kathmandu" },
  { value: "Asia/Novosibirsk", text: "Novosibirsk" },
  { value: "Asia/Almaty", text: "Almaty" },
  { value: "Asia/Dacca", text: "Dacca" },
  { value: "Asia/Krasnoyarsk", text: "Krasnoyarsk" },
  { value: "Asia/Dhaka", text: "Astana, Dhaka" },
  { value: "Asia/Bangkok", text: "Bangkok" },
  { value: "Asia/Saigon", text: "Vietnam" },
  { value: "Asia/Jakarta", text: "Jakarta" },
  { value: "Asia/Irkutsk", text: "Irkutsk, Ulaanbaatar" },
  { value: "Asia/Shanghai", text: "Beijing, Shanghai" },
  { value: "Asia/Hong_Kong", text: "Hong Kong" },
  { value: "Asia/Taipei", text: "Taipei" },
  { value: "Asia/Kuala_Lumpur", text: "Kuala Lumpur" },
  { value: "Asia/Singapore", text: "Singapore" },
  { value: "Australia/Perth", text: "Perth" },
  { value: "Asia/Yakutsk", text: "Yakutsk" },
  { value: "Asia/Seoul", text: "Seoul" },
  { value: "Asia/Tokyo", text: "Osaka, Sapporo, Tokyo" },
  { value: "Australia/Darwin", text: "Darwin" },
  { value: "Australia/Adelaide", text: "Adelaide" },
  { value: "Asia/Vladivostok", text: "Vladivostok" },
  { value: "Pacific/Port_Moresby", text: "Guam, Port Moresby" },
  { value: "Australia/Brisbane", text: "Brisbane" },
  { value: "Australia/Sydney", text: "Canberra, Melbourne, Sydney" },
  { value: "Pacific/Noumea", text: "Noumea" },
  { value: "Asia/Magadan", text: "Magadan" },
  { value: "Pacific/Fiji", text: "Fiji" },
  { value: "Asia/Kamchatka", text: "Kamchatka" },
  { value: "Pacific/Auckland", text: "Auckland" },
  { value: "Pacific/Tongatapu", text: "Nuku'alofa" },
];

const stateAbbreviations = {
  alabama: "AL",
  alaska: "AK",
  arizona: "AZ",
  arkansas: "AR",
  california: "CA",
  colorado: "CO",
  connecticut: "CT",
  district_of_columbia: "DC",
  delaware: "DE",
  florida: "FL",
  georgia: "GA",
  hawaii: "HI",
  idaho: "ID",
  illinois: "IL",
  indiana: "IN",
  iowa: "IA",
  kansas: "KS",
  kentucky: "KY",
  louisiana: "LA",
  maine: "ME",
  maryland: "MD",
  massachusetts: "MA",
  michigan: "MI",
  minnesota: "MN",
  mississippi: "MS",
  missouri: "MO",
  montana: "MT",
  nebraska: "NE",
  nevada: "NV",
  new_hampshire: "NH",
  new_jersey: "NJ",
  new_mexico: "NM",
  new_york: "NY",
  north_carolina: "NC",
  north_dakota: "ND",
  ohio: "OH",
  oklahoma: "OK",
  oregon: "OR",
  pennsylvania: "PA",
  rhode_island: "RI",
  south_carolina: "SC",
  south_dakota: "SD",
  tennessee: "TN",
  texas: "TX",
  utah: "UT",
  vermont: "VT",
  virginia: "VA",
  washington: "WA",
  west_virginia: "WV",
  wisconsin: "WI",
  wyoming: "WY",
  american_samoa: "AS",
  guam: "GU",
  northern_mariana_islands: "MP",
  puerto_rico: "PR",
  united_states_minor_outlying_islands: "UM",
  virgin_islands: "VI",
};
export const getTwoLettersOfStates = (stateName) => {
  const abbreviation = stateAbbreviations[stateName?.toLowerCase()];
  return abbreviation || "Unknown State";
};
